name: Docker build and publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Hugo themes are git submodules: "submodules: true" needed
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      #Replace IMG_TAG variable with github.sha for image versioning
      - name: Generate deploy yaml
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: template-deploy.yaml
          output: my-deploy.yaml
        env:
          IMG_TAG: ${{ github.sha }}
      # Docker build and publish
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: fsemeraro96/hugo-site
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      #Deploy website on k8s cluster (crownlabs)
      - name: Deploy website on K8s cluster
        uses: giorio94/kubectl-oidc-action@1.1.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f my-deploy.yaml --namespace=sandbox-s291498
      #Copy content on github.io site
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'franckies'
          destination-repository-name: 'franckies.github.io'
          user-email: fk.semeraro@gmail.com
          commit-message: CI Commit by mywebsite for version ${{ github.sha }}.
          target-branch: master

